### ISSUE TITLE
docs.rs: Documentation build failure

### ISSUE THREAD

**Issue by silvergasp** [facebookexperimental/starlark-rust#106]
The docs.rs build of the latest documentation is failing https://docs.rs/crate/starlark/0.10.0/builds/1053872. This is not a deal breaker but slightly annoying when using starlark-rust as I'll typically have docs.rs open to one side while I develop.

**Comment by ndmitchell** [comment]
I suspect we need a release with https://github.com/facebookexperimental/starlark-rust/commit/c201c5e3117641c0b8c6f3d1c9408c9345690500. I might go through the active PR's and then make a new release.

**Comment by ndmitchell** [comment]
Release made. Watching the docs website 👀

**Comment by ndmitchell** [comment]
https://docs.rs/starlark/latest/starlark/ seems to be happy, so closing this. I switched to using stable by default, so hopefully it remains working as things go forward, without nightly breakages.

**Comment by silvergasp** [comment]
Thanks for being so responsive!
