### ISSUE TITLE
test cases should not depend on @bazel_tools//tools/build_defs/pkg:pkg.bzl

### ISSUE THREAD

**Issue by aiuto** [facebookexperimental/starlark-rust#21]
pkg_tar from @bazel_tools//tools/build_defs/pkg might go away at Bazel 5.x.

It is referenced here and in a few other places
https://github.com/facebookexperimental/starlark-rust/blob/b5df9fe72616a5879e760d563b19a6103ce57168/starlark/testcases/parse/jenkins_base.star#L23

AFAICT, this is harmless, since you do not evaluate using bazel semantics, you are just checking that you can parse things. This is more of a heads up in case you think that will be an issue one day.

**Comment by ndmitchell** [comment]
Thanks for the heads up, I appreciate it! You're right, we use this code only for parsing tests, so we're good, and have no plan to every switch to evaluation for these files. The only `.star` files we evaluate are those in https://github.com/facebookexperimental/starlark-rust/tree/master/starlark/testcases/eval/go, which don't have any load's and were taken from the Go Starlark implementation.
