### ISSUE TITLE
starlark-rust allows string.startswith to take a list as value of its prefix parameter, contrary to language spec

### ISSUE THREAD

**Issue by tetromino** [facebookexperimental/starlark-rust#23]
starlark-rust allows the following: `'a'.startswith(['a'])`

By contrast, java and go starlark implementations allow only a string or a tuple of strings as the prefix parameter, in accordance with the spec: https://github.com/bazelbuild/starlark/blob/master/spec.md#string%C2%B7startswith

(Arguably, starlark-rust's behavior is better here - so maybe we ought to change the spec...)

**Comment by tetromino** [comment]
... and same for `'a'.endswith(['a'])`

**Comment by ndmitchell** [comment]
I think the correct Starlark thing would be either to accept all iterables, or just tuples. Given that the Rust one accepts lists and tuples that seems wrong. I'll switch to just tuples.

**Comment by ndmitchell** [comment]
Fixed in 5b888f6ad062cb70c7744bb6427e4039e1a310a7
