### ISSUE TITLE
Is VSCode extension functional?

### ISSUE THREAD

**Issue by vadimcn** [facebookexperimental/starlark-rust#26]
I've compiled and installed it, but it does not seem to do anything...   Is this expected?

**Comment by ndmitchell** [comment]
It works for me - I'm using it every day. Can you check that `starlark` is on your PATH, that the extension is installed. Do you see syntax highlighting for `.sky` files?

**Comment by vadimcn** [comment]
I tried to use it on Bazel BUILD files (which I did mark as lang=Starlark).  I saw syntax highlighting, but assumed it's just regex matching.    I'm looking for an extension that can help with navigation around a Bazel project ("Go To Definition", "Find References", etc).  Is this not what your extension does?

**Comment by ndmitchell** [comment]
Indeed, the syntax highlighting is Regex based, but let's us figure out whether the extension itself is installed. If you are using Bazel BUILD files I recommend using https://marketplace.visualstudio.com/items?itemName=BazelBuild.vscode-bazel - it's from the Bazel team. This project is for more pure Starlark code, has great support for linting, some for debugging, but doesn't yet do goto definition/find reference (although it will one day).

**Comment by vadimcn** [comment]
>  If you are using Bazel BUILD files I recommend using https://marketplace.visualstudio.com/items?itemName=BazelBuild.vscode-bazel - it's from the Bazel team.

Yes, I'm using this one, but it doesn't do Go To Definition either.   

I suppose I had wrong expectations for this extension, so I'll just close this.   Thanks!

**Comment by ndmitchell** [comment]
This extension is meant to work with Starlark files, but where an import actually goes to is outside the Starlark spec, so the only real thing that can deal with that properly is the tool that embeds Starlark into it.
