### ISSUE TITLE
Build broken on MacOs

### ISSUE THREAD

**Issue by GaryBoone** [facebookexperimental/starlark-rust#28]
Did something just update in the past few hours that breaks the build on macOs? My code now fails to compile, showing this error:

    Basic Block in function '_ZN7lalrpop3tok9Tokenizer10take_until17h0db094dbe1039a64E' does not have terminator!
    label %9
    in function _ZN7lalrpop3tok9Tokenizer10take_until17h0db094dbe1039a64E
    LLVM ERROR: Broken function found, compilation aborted!
    error: could not compile `lalrpop`

...which `$ cargo tree` shows is being imported by `starlark-rust`:

    ├── starlark v0.4.0 (https://github.com/facebookexperimental/starlark-rust#094f681e)
    ...
    │   ├── lalrpop-util v0.19.6
    │   │   └── regex v1.5.4 (*)

**Comment by ndmitchell** [comment]
Unfortunately this is a bug in the latest Rust nightly - https://github.com/rust-lang/rust/issues/88043. If you specify an older nightly in the Rust tool chain it should work for you.

**Comment by GaryBoone** [comment]
Ok, this works:

    $ rustup default nightly-2021-08-15

Even though the bug is not in `starlark-rust`, I propose leaving this bug open for visibility to other `starlark-rust` users who might have the same problem. 

BTW, speaking of stability, are there plans for a new release of `starlark-rust` and `starlark-module`?  Following [this issue](https://github.com/facebookexperimental/starlark-rust/issues/22#issuecomment-859591486), I'm using HEAD to pull the code that removes some heap arguments. Depending on a released version would reduce change risk...

**Comment by ndmitchell** [comment]
Yep, happy to keep the task open. Although my CI tests _just_ started passing, so I think if you try nightly again now it should work?

I'll put it on my todo list to make a starlark-rust release this week. Makes sense to do another one.

**Comment by ndmitchell** [comment]
Closing this issue, but tracking the release as #29
