### ISSUE TITLE
LSP: code completion

### ISSUE THREAD

**Issue by laurentlb** [facebookexperimental/starlark-rust#52]
Hi,

Thanks to @DanielEliad's PR (#51), I've noticed the LSP code in the repo. It's very nice to see an update on this!

I think it's important to keep the LSP generic enough to accomodate multiple dialects of Starlark. I imagine you'll need it at Facebook too. Our approach at Google was to define a proto file that contains all the definitions for a dialect (all the builtins, all the types, all the methods on the types).

- Proto definition: https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/builtin.proto
- Executable that generates the proto definitions for Bazel: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/docgen/ApiExporter.java

It would be very useful to align on this and use a compatible solution.

**Comment by cameron-martin** [comment]
I presume this is what [`LspContext#get_environment`](https://docs.rs/starlark_lsp/latest/starlark_lsp/server/trait.LspContext.html#tymethod.get_environment) does?

**Comment by ndmitchell** [comment]
Yep, we're not going to do a proto-based completion, but given the LspContext hooks, someone could easily do that themselves, so closing this.
