### ISSUE TITLE
ansi_term dependency issue

### ISSUE THREAD

**Issue by palfrey** [facebookexperimental/starlark-rust#55]
This project depends on structopt, which depends on clap v2, which depends on ansi_term [which is unmaintained](https://rustsec.org/advisories/RUSTSEC-2021-0139.html).

There's a [migration guide](https://github.com/clap-rs/clap/blob/v3-master/CHANGELOG.md#migrating) available to be able to fix this.

**Comment by ndmitchell** [comment]
I think the plan is to move to clap v3 in due course. Is this causing you any specific issues? Or just a case of noticing something and reporting it?

**Comment by palfrey** [comment]
Noticing and reporting mainly. I can't fix this dependency fully in a project of mine because of this, but it's not a big deal TBH, just annoying!
