### ISSUE TITLE
impl UnpackValue for f64

### ISSUE THREAD

**Issue by benmkw** [facebookexperimental/starlark-rust#71]
When writing a rust function which should be called by stacklack which accepts a float one currently one has to accept a Value and then do 

```rs
val.unpack_num().unwrap().as_float()
```

The error message if one uses a float in a `#[starlark_module]` is somewhat surprising because floats are listed as primitives https://github.com/bazelbuild/starlark/blob/master/spec.md#data-types

**Comment by ndmitchell** [comment]
Agreed, I'll write a patch now. Floats got added latter, so I guess this got missed.

**Comment by ndmitchell** [comment]
Done in 4b7005e3e752acc5a5de122e0232317808fd225d.
