### ISSUE TITLE
Add support for dict union

### ISSUE THREAD

**Issue by dreiss** [facebookexperimental/starlark-rust#75]
Added to upstream at https://github.com/bazelbuild/starlark/pull/215

**Comment by dtolnay** [comment]
I believe this is already implemented. https://github.com/facebookexperimental/starlark-rust/commit/37f87baa54d15f137ed7ea5c1d9796354aeae391

https://github.com/facebookexperimental/starlark-rust/blob/5e767e2a170b23b780a2c74ef7971e4357464425/starlark/src/values/types/dict/value.rs#L461

**Comment by dreiss** [comment]
Ah, yes.  I was confused by another tool that was processing my Starlark file and failing on this.  Thanks!
