### ISSUE TITLE
Add a --version flag

### ISSUE THREAD

**Issue by stagnation** [facebookexperimental/starlark-rust#76]
Hi!

I am a happy user, mainly for Bazel work, but have been very pleased with the release of Buck2.
Now I find myself with multiple builds of the program as I try to follow the new features as they land in here,
rather than wait for official releases of the cargo package.

Each time I rebase though I find myself typing `starlark --version`, and realize that it does not tell me a version.

That said, I'm a happy mono-repo developer and mostly live at head, and I know of the headache build stamping leads to.
But I feel that a version flag would still be useful,a stamped shaid and the commit date would be nice.

**Comment by ndmitchell** [comment]
I think this is probably a issue request for https://github.com/facebook/buck2? I imagine you want to do `buck2 --version`?

**Comment by ndmitchell** [comment]
Added in 863cfe75ad9b16bd732c1c8f2ed5edbc8f69f8da - shows the Cargo.toml version.
