### ISSUE TITLE
LSP fails on startup if prelude has error

### ISSUE THREAD

**Issue by cjhopman** [facebookexperimental/starlark-rust#88]
If there's an issue in the prelude when the starlark lsp starts up, it just crashes, does it 5 times and then gets disabled by vscode.

**Comment by ndmitchell** [comment]
I suspect this is a bug in how Buck2 integrates with the Starlark LSP, rather than the Starlark LSP itself.

**Comment by cjhopman** [comment]
Yep, it definitely is.
