### ISSUE TITLE
lsp jump to definition bad behavior

### ISSUE THREAD

**Issue by cjhopman** [facebookexperimental/starlark-rust#90]
often when doing jump-to-definition on a field, it just jumps me to the top of the current file. this is worse than doing nothing.

**Comment by stagnation** [comment]
I see this too with the bazel mode:

```
def aspect_impl(target, ctx):
     name = ctx.rule.attr.name
     ...
```

Jumping from the `name` member of `ctx.rule.attr` goes to the top for me,
and some builtin methods/functions. `<list variable>.append(<x>)` jumps to the top from `append`.
Also `ctx.actions.write` from `write`.

**Comment by MaartenStaa** [comment]
@stagnation Ah, interesting, thanks for the insight! In general I would say anything that uses dotted definitions (`foo.bar`) have very poor support at the moment in the LSP. Most functionality in such cases defers to the first segment (i.e. `foo`) in this example, but maybe that leads to some weird edge cases with go to definition.
