### ISSUE TITLE
enum/ record/ string types don't work anymore in standard dialect (doc question)

### ISSUE THREAD

**Issue by benmkw** [facebookexperimental/starlark-rust#94]
the following code does not work anymore:

```rust
fn main() {
    let content = include_str!("./main.star");
    let ast = AstModule::parse(
        "main.star",
        content.to_owned(),
        &Dialect {
            enable_types: DialectTypes::Enable,
            enable_def: true,
            ..Dialect::Standard
        },
    )
    .unwrap();
    let globals = GlobalsBuilder::new().build();
    let module = Module::new();
    let mut eval = Evaluator::new(&module);
    eval.enable_static_typechecking(true);
    eval.eval_module(ast, &globals).unwrap();
}

```

`rt = enum("one", "two")`

```
 --> main.star:1:6
  |
1 | rt = enum("one", "two")
  |      ^^^^
  |
```

and also 

```
def hello(input : str) -> str:
     return input + "world"
```

```
 --> main.star:1:19
  |
1 | def hello(input : str) -> str:
  |                   ^^^
  |
```

and

```
 --> main.star:1:1
  |
1 | print(hello("world"))
  | ^^^^^
  |
```

I saw a commit which changed `str.type` to `str` but could not find a way to enable it, probably I'm missing some basic config option?

**Comment by stepancheg** [comment]
```
GlobalsBuilder::new().build()
```

creates empty globals. I'm not sure this ever worked.

**Comment by stepancheg** [comment]
P.S. Next time when reporting bugs, please include full error. I think message (which is omitted) states that symbol is not resolved.

**Comment by benmkw** [comment]
thanks for the quick response, `GlobalsBuilder::extended_by` worked

> I think message (which is omitted) states that symbol is not resolved.

somehow I only looked at the dialect type and thought that its settings would enable all the things because `enable_types: DialectTypes::Enable` seemed to me like it would include e.g. `starlark::environment::LibraryExtension::RecordType` but on second though thats of course not true cause it can be enabled with only custom types as well so these two settings are somewhat orthogonal.

on the other hand `starlark::environment::LibraryExtension::Typing` seems like it is closely related to `Dialect.enable_types` so maybe there is still an opportunity to unify both/ combine them somewhat

**Comment by ndmitchell** [comment]
The idea is that `LibraryExtension` is changing your standard library, whereas `enable_types` is changing your parser. You can still write some types without the `LibraryExtension` (e.g. `str`), it's just things like `typing.Any` that doesn't make a whole lot of sense without the other. I've created an internal patch to make each reference the other, which should be in the repo later today.
